### ISSUE TITLE
Unable to open save file from Journey to the Savage Planet

### ISSUE THREAD

**Issue by qwandor** [trumank/uesave-rs#13]
I'm trying to figure out why my save files from Journey to the Savage Planet on Stadia aren't working on the Steam version, and so being able to compare them would be useful. Unfortunately there seems to be a bug preventing uesave from reading them:

 ```
$ uesave to-json < save.bin
Error: unknown property type: "TextLanguage"
```

I've attached a zip file containing the save file.

[Journey to the Savage Planet_1001_gamesave.zip](https://github.com/trumank/uesave-rs/files/13708548/Journey.to.the.Savage.Planet_1001_gamesave.zip)

**Comment by trumank** [comment]
This save is a pretty good test case, so thanks for uploading it! Finally took the time to property implement text properties from the ground (still incomplete as text localization stuff is huge, but the groundwork is there now).

It also features an `FName` array which gets serialized as a two-member struct with each member having the same key name. I made the assumption member names have to be unique so to fix it requires some pretty significant changes to the API which hampers JSON readability quite a bit. I implemented a possible solution (store property key/value pairs in a vec instead of in a map) [here](https://github.com/trumank/uesave-rs/tree/duplication-index), but I'm hoping there's a better solution before merging it. For now, this save will parse without error but there will be a member missing from the `TrackedQuestsNames` array in the resulting JSON.
