### ISSUE TITLE
Found non-standard magic, io error: failed to fill whole buffer, not Palworld, ue5.4

### ISSUE THREAD

**Issue by Egaliterrier** [trumank/uesave-rs#42]
Game is Serum, running on UE 5.4, getting this message:

> Found non-standard magic: [c1, 83, 2a, 9e] (��*�) expected: GVAS, continuing to parse...
> Error: at offset 12309: io error: failed to fill whole buffer

[Player.zip](https://github.com/trumank/uesave-rs/files/15444619/Player.zip)

**Comment by trumank** [comment]
I believe this save has been compressed with `FArchive::SerializeCompressedNew` which does some kind of block compression (blocks are marked with `C1 83 2A 9E 22 22 22 22`.)

**Comment by trumank** [comment]
I'm not sure yet. It seems to be a newly added function for general purpose compression, so if it ends up being used by a lot of games, it might be worth supporting.

**Comment by trumank** [comment]
I hacked together a script to decompress the save (uses Oodle compressor too🤮) and the decompressed file actually is actually not quite a normal UE save. It lacks the GVAS magic and header, but otherwise does look like UE tagged serialization. It'd be doable to parse but would take a bit of work and I think is safely out of the scope of this tool.

[uncompressed.zip](https://github.com/user-attachments/files/15778624/uncompressed.zip)
